name: jake_flutter
description: Flutter bridge for Jake Messenger.
version: 0.1.0
homepage: https://tryjake.ai

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: ai.tryjake.flutter
        pluginClass: JakeFlutterPlugin
      ios:
        pluginClass: JakeFlutterPlugin
